#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-

local Qvar=$1
integer verbose=$2

shift
local -A Opts=( "${(kv@)${(@PAkv)Qvar}}" )
local -a items

local -TU CMD_PATH=$CMD_COMMAND_PATH cmd_path
csrv-filter-dirs $verbose $cmd_path || return 1

(( ! $#reply ))&&{
    msg {208}Error:%f%b No command dirs found, set {39}\$CMD_COMMAND_PATH%f \
    first
    return 3
}

items=( $^cmd_path/*.(ini|cmd)(N) )
(( ! $#items ))&&{
    msg {208}Error:%f%b No commands found in {39}CMD_COMMAND_PATH%f%b
    return 5
}

local -aU pth
local p q
pth=( ${items:h} )
for q in $pth; do
    msg In {203}%B$q%f%b:
    for p in ${(M)items:#$q/*}; do
        msg {203}$p:t:
        grep --line-number $@ $p
    done
done

return exit_code
# vim:ft=zsh:tw=80:sw=4:sts=4:et:foldmarker=[[[,]]]
