#!/usr/bin/env zsh

csrv-extend-iocmd-text() {
    local text=$1 q=$2 with=$3 char v excl
    local -a arr
    REPLY=
    arr=( "${(@Q)${(@z)with}}" )
    for v in $arr; do
        if [[ $q == 0 ]]; then
            char="0<"
        elif [[ $q == 1 ]]; then
            char="1>"
        elif [[ $q == 2 ]]; then
            char="2>"
        fi

        excl=${${(M)v#\!}:+\>}
        v=${v#\!}

        # Redirection of stdin
        [[ $v != std(in|out|err) && $q == 0 ]] && text+="0<$stdin"
        [[ $v == stdin && $q == 0 ]] && text+=" 0< <(cat)"
        [[ $v == stdout && $q == 0 ]] && text+=" 0<&1"
        [[ $v == stderr && $q == 0 ]] && text+=" 0<&2"

        # Redirection of stdout
        [[ $v != std(out|err|in) && $q == 1 ]] && text+=" 1>$excl$v"
        [[ $v == stdout && $q == 1 ]] && text+=" 1> >(cat)"
        [[ $v == stdin && $q == 1 ]] && text+=" 1>&0"
        [[ $v == stderr && $q == 1 ]] && text+=" 1>&2"

        # Redirection of stdin
        [[ $v != std(err|out|in) && $q == 2 ]] && text+=" 2>$excl$stderr"
        [[ $v == stderr && $q == 2 ]] && text+=" 2> >(cat >&2)"
        [[ $v == stdout && $q == 2 ]] && text+=" 2>&1"
        [[ $v == stdin && $q == 2 ]] && text+=" 2>&0"
    done
    REPLY=$text
}

# vim:ft=zsh:sw=4:sts=4:ts=8:et
