#!/usr/bin/env zsh

csrv-replace-vars() {
    local var_name=$1 sec_name=vars k v var
    local -A vars
    local -a tmp

    vars=( "${(@kv)${(@PAkv)var_name}[(I)vars__*]}" )

    for k v in ${(@kv)vars}; do
        var=${k##vars__}
        tmp=( ${${(@kv)${(@PAkv)var_name}}//\%$var/$v} )
        : ${(@AP)var_name::="$tmp[@]"}
    done
}

# vim:ft=zsh:sw=4:sts=4:ts=8:et
