#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-

local Qvar=$1
integer verbose=$2

shift
local -A Opts=( "${(kv@)${(@PAkv)Qvar}}" )
local -a items

local -TU CMD_PATH=$CMD_COMMAND_PATH cmd_path
csrv-filter-dirs $verbose $cmd_path || return 1

(( ! $#reply ))&&{
    msg {208}Error:%f%b No command dirs found, set {39}\$CMD_COMMAND_PATH%f \
    first
    return 3
}

items=( $^cmd_path/*.(ini|cmd)(N) )
(( ! $#items ))&&{
    msg {208}Error:%f%b No commands found in {39}CMD_COMMAND_PATH%f%b
    return 5
}

local -aU pth
local q p i u
pth=( ${items:h} )
for q in $pth; do
    msg In {203}%B$q%f%b:
    for p in ${(M)items:#$q/*}; do
        Opts=()
        @str-read-toml $p Opts
        i=
        [[ $Opts[main__disabled] == (1|yes|true) ]] && u=" {203}disabled%f,"
        [[ $Opts[main__disabled] == manual ]] && u=" {208}manual only%f,"
        msg - {39}${p##$q/##}%f,$u
    done
done

return exit_code
# vim:ft=zsh:tw=80:sw=4:sts=4:et:foldmarker=[[[,]]]
