#!/usr/bin/zsh

local -a in_src_dirs=($@) tmp
reply=()
local qdir

# Iterate over given dirs.
for qdir in $in_src_dirs; do
    tmp=( $qdir/*.(ini|cmd)(N) )
    if [[ ! -d $qdir || ! -r $qdir ]]; then
        msg {208}Error{39}:{70} Directory \`{39}$qdir{70}\` \
            incorrect, skipping…
    else
        if [[ -z $tmp ]]; then
            msg {208}Warning{39}:{70} Directory \`{39}$qdir{70}\` \
                doesn\'t contain any command definitions.
        fi
        reply+=( $qdir )
    fi
done

# Final check.
if ((!$#reply)); then
    msg {208}Error{39}:{70} No suitable directories found, \
            exiting the {cmd}command-server{70}…
    return 1
fi
return 0

# vim:ft=zsh:sw=4:sts=4:ts=8:et
